---
title: "PBHL621 data cleaning and visualization project"
author: "Ethan Walker"
date: "Feb 11th and 13th, 2020"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include=FALSE, eval=TRUE, echo=FALSE,
                      warning = FALSE, error = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(gmodels)
```

# Try out what we've learned

Try to duplicate some summary statistics and plots using the code we have
gone through together. Most of it we have gone through; a few things you 
might need to troubleshoot on your own.

## Load full dataset
```{r}
nsch_practice <- read_xlsx("Input/nsch_practice.xlsx")
```

## Clean the variables of interest
```{r}
nsch_clean <- nsch_practice %>% 
   # start by cleaning the variables
   mutate(sex = as.factor(SC_SEX),
          age_child = as.numeric(SC_AGE_YEARS),
          age_mom = as.numeric(MOMAGE)) %>% 
   # replace values with NA
   replace_with_na(sex, replace = list(sex = c(0, 7, 99))) %>% 
   replace_with_na(age_child, replace = list(age_child = c(99))) %>% 
   replace_with_na(age_mom, replace = list(age_mom = c(98, 99))) %>%
   # clean language and create new labels
   mutate(language = fct_collapse(HHLANGUAGE,
                                  "english" = c("1", "english"),
                                  "spanish" = c("2", "spanish"),
                                  "french" = "3",
                                  "NA" = c("99", "??", "0"))) %>% 
   replace_with_na(language, replace = list(language = c("NA"))) %>%
   # Create new categorical variable for child age (and format sex)
   mutate(sex = factor(sex, levels = c("1", "2"), labels = c("male", "female")),
          age_child_cat = cut(age_child, breaks = c(0, 6, 11, 18),
                              labels = c("0 to 5", "6 to 10", "11+"),
                              right = FALSE)) %>% 
   # select the variables you want to work with
   select(sex, age_child, age_child_cat, age_mom, language) 
   
head(nsch_clean, 10)
summary(nsch_clean)
```

## Summarize the data to fill in the table
```{r}
# age_child
age_numeric <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   group_by(sex) %>% 
   summarize("n" = n(),
             "Mean" = mean(age_child, na.rm = TRUE),
             "SD" = sd(age_child, na.rm = TRUE),
             "Min" = min(age_child, na.rm = TRUE),
             "Max" = max(age_child, na.rm = TRUE))
age_numeric


# age_child_cat
age_cat <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   group_by(age_child_cat) %>% 
   summarize("n" = n(),
             "%" = n()/95)
age_cat

# age_child_cat - male
age_cat_male <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   filter(sex == "male") %>% 
   group_by(age_child_cat) %>% 
   summarize("n" = n(),
             "%" = n()/53)
age_cat_male

# age_child_cat - female
age_cat_female <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   filter(sex == "female") %>% 
   group_by(age_child_cat) %>% 
   summarize("n" = n(),
             "%" = n()/42)
age_cat_female
```


```{r}
# age_mom
age_mom_numeric <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   #group_by(sex) %>% 
   summarize("n" = n(),
             "Mean" = mean(age_mom, na.rm = TRUE),
             "SD" = sd(age_mom, na.rm = TRUE),
             "Min" = min(age_mom, na.rm = TRUE),
             "Max" = max(age_mom, na.rm = TRUE))
age_mom_numeric
```


```{r}
# language
language <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   group_by(language) %>% 
   summarize("n" = n(),
             "%" = n()/95)
language

# language - male
language_male <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   filter(sex == "male") %>% 
   group_by(language) %>% 
   summarize("n" = n(),
             "%" = n()/53)
language_male

# language - female
language_female <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   filter(sex == "female") %>% 
   group_by(language) %>% 
   summarize("n" = n(),
             "%" = n()/42)
language_female
```


## Make a plot to summarize the data:
```{r, include=TRUE, eval=TRUE, echo=FALSE, fig.height=5, fig.width=6.5}
nsch_barplot <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   ggplot() +
     geom_bar(aes(age_child_cat, fill = language), color = "black") +
     theme_minimal() +
     scale_fill_manual(values = c("#E69F00", "#009E73", "#56B4E9", "#D55E00")) +
     labs(title = "Child age categories and language",
          subtitle = "Grouped by sex of the child",
          fill = "Household language") +
     xlab("Age category (years)") +
     ylab("Number of children") +
     theme(title = element_text(size = 16),
           axis.title = element_text(size = 14),
           axis.text.x = element_text(size = 11, angle = 20, color = "black"),
           axis.text.y = element_text(size = 11, angle = 20, color = "black"),
           legend.text = element_text(size = 14),
           panel.grid = element_blank(),
           axis.line.x.bottom = element_line(color = "black", size = 1),
           axis.line.y.left = element_line(color = "black", size = 1),
           strip.text.x = element_text(size = 14, color = "black")) +
     facet_wrap(~sex)
nsch_barplot
```


## Try another if you have time:
```{r, include=TRUE, eval=TRUE, echo=FALSE, fig.height=5, fig.width=6.5}
nsch_barplot_2 <- nsch_clean %>% 
   filter(!is.na(sex)) %>% 
   mutate(age_mom_cat = cut(age_mom, breaks = c(18, 25, 35, 45),
                              labels = c("18 to 24", "25 to 34", "35+"),
                              right = FALSE)) %>% 
   ggplot() +
     geom_bar(aes(age_child_cat, fill = age_mom_cat), color = "black") +
     theme_minimal() +
     scale_fill_manual(values = c("#E69F00", "#009E73", "#56B4E9", "#D55E00")) +
     labs(title = "Child age categories and mother's age",
          subtitle = "Grouped by sex of the child",
          fill = "Mother's age") +
     xlab("Age category (years)") +
     ylab("Number of children") +
     theme(title = element_text(size = 16),
           axis.title = element_text(size = 14),
           axis.text.x = element_text(size = 11, angle = 20, color = "black"),
           axis.text.y = element_text(size = 11, angle = 20, color = "black"),
           legend.text = element_text(size = 14),
           panel.grid = element_blank(),
           axis.line.x.bottom = element_line(color = "black", size = 1),
           axis.line.y.left = element_line(color = "black", size = 1),
           strip.text.x = element_text(size = 14, color = "black")) +
     facet_wrap(~sex)
nsch_barplot_2
```