---
title: "PBHL621 class and data prep"
author: "Ethan Walker"
date: "Started 27 Jan 2020, 29 Jan 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
```

# Load full dataset
```{r}
nsch_data_full <- read_csv("Input/nsch_2017_2018_data_full.csv")

# data has 52,129 observations and 745 variables
```

# Pull subsets of the data and save as CSV
```{r}
# filter for 2017 data
nsch_data_2017 <- nsch_data_full %>% 
   filter(str_detect(HHID, "^17"))

# save subset of data
write_csv(nsch_data_2017, "Output/nsch_data_2017.csv")
write_rds(nsch_data_2017, "Output/nsch_data_2017.rds")


# filter for 2018 data
nsch_data_2018 <- nsch_data_full %>% 
   filter(str_detect(HHID, "^18"))

# save subset of data
write_csv(nsch_data_2018, "Output/nsch_data_2018.csv")
write_rds(nsch_data_2018, "Output/nsch_data_2018.rds")
```

# Make some intentional errors in the CSV file, then reload
```{r}

```

